CREATE DATABASE IF NOT EXISTS DominoOnline;

USE DominoOnline;

CREATE TABLE Room (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Code VARCHAR(255),
    Name VARCHAR(255),
    Created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE Games (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NameUser VARCHAR(255) NOT NULL,
    Data TEXT,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Room_ID INT,
    FOREIGN KEY (Room_ID) REFERENCES Room(ID)
);

CREATE TABLE Ranking (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Score INT NOT NULL,
    Room_ID INT,
    FOREIGN KEY (Room_ID) REFERENCES Room(ID)
);
