CREATE DATABASE IF NOT EXISTS dominoonline;

USE dominoonline;

CREATE TABLE Room (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Code VARCHAR(255) COLLATE utf8_bin UNIQUE,
    Name VARCHAR(255),
    Created_at DATETIME(3) DEFAULT CURRENT_TIMESTAMP(3)
);

CREATE TABLE Games (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NameUser VARCHAR(255) NOT NULL,
    Data TEXT,
    Timestamp DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    Room_ID INT,
    FOREIGN KEY (Room_ID) REFERENCES Room(ID)
);

CREATE TABLE Ranking (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Score INT NOT NULL,
    Room_ID INT,
    Game_ID INT UNIQUE,
    FOREIGN KEY (Room_ID) REFERENCES Room(ID)
);
